City:
 - "Port Royale"
 - "Tortuga"
 - "Tortage"
 - "Belle île"
 - "Mirage"
 - "Blue Lagon"
 - "Dunkerque"
 - "Saigon"
 - "Maracaibo"
 - "Fort de la Roche"
 - "Mahebourg"
 - "Guajira"
Resource:
 - "Bois"
 - "Coton"
 - "Tissu"
 - "Tabac"
 - "Rhum"
 - "Fer"
 - "Armes"
 - "Rubis"
 - "Ivoire"
 - "Soie"
 - "Diamant"
 - "Opium"
